steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Fetch the service account key from Secret Manager and save it to a file
    gcloud secrets versions access latest --secret=gcloud-service-key > /workspace/gcloud-service-key.json
    export GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcloud-service-key.json

    # Deploy the Cloud Function
    gcloud functions deploy helloWorld \
      --runtime nodejs14 \
      --trigger-http \
      --allow-unauthenticated \
      --region us-central1

options:
  logging: CLOUD_LOGGING_ONLY  # Set logging to cloud logging only
timeout: 1200s