steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['secrets', 'access', 'gcloud-service-key', '--format=value']
  entrypoint: 'bash'
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcloud-service-key.json'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'helloWorld', '--runtime', 'nodejs14', '--trigger-http', '--allow-unauthenticated', '--region', 'us-central1']
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcloud-service-key.json'

timeout: 1200s
